builds:
  - ldflags:
      - -s -w -X github.com/khlieng/dispatch/version.Tag=v{{.Version}} -X github.com/khlieng/dispatch/version.Commit={{.ShortCommit}} -X github.com/khlieng/dispatch/version.Date={{.Date}}

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

archives:
  - files:
      - none*

    format_overrides:
      - goos: windows
        format: zip

    replacements:
      amd64: x64
      darwin: mac

checksum:
  name_template: "checksums.txt"

changelog:
  filters:
    exclude:
      - "(?i)^update.*dep"
      - Merge pull request
      - Merge branch

release:
  name_template: "{{.Version}}"
